apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmdeployment
  namespace: default
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      tier: frontend
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: millicent25/my-app-port86:latest
        ports:
        - containerPort: 86
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 50 milli cores (1/20 CPU)
          limits:
            memory: "128Mi" # 128 mebibytes 
            cpu: "100m"