apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmdeployment
  namespace: default
  labels:
    app: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: millicent25/nginxweb-app:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "5Mi" 
            cpu: "5m"    # 50 milli cores (1/20 CPU)
          limits:
            memory: "5Mi" # 128 mebibytes 
            cpu: "5m"
